### ISSUE TITLE
Is there any way to minimize full screen video if some state change?

### ISSUE THREAD

**Issue by sabit990928** [u-wave/react-youtube#101]
@goto-bus-stop @fawaf @Authchirion. I have a case when there is paused state change(not manually), when it happens I want to minimize the video. Do you have any idea how call it?

**Comment by goto-bus-stop** [comment]
The YouTube API doesn't have a fullscreen API, but the DOM APIs provided by the browser should do the trick here. You can call [`document.exitFullscreen()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/exitFullscreen) in an `onPause` function:

```js
<YouTube
  onPause={() => {
    if (document.fullscreenElement)
      document.exitFullscreen()
  }}
/>
```

**Comment by sabit990928** [comment]
@goto-bus-stop, thanks it works for me
