### ISSUE TITLE
Autoplay false doesn't work on async video data

### ISSUE THREAD

**Issue by cjmling** [u-wave/react-youtube#24]
I am trying to async query video on `componentDidMount` and then display the player based on the loaded video.  

**Problem:** Everything work , video can be play. But the player always autoplay the video. 

Sample codes

```
class VideoPage extends Component {
    	constructor(props) {
        	super(props);
       		this.state = {
            		video: {},
        	};
    	}
    	componentDidMount() {
        	this.getVideo(this.state.videoId);
    	}
   	getVideo(){
		// query db then
		this.setState(video);	
	}

	return(){
		const {video} = this.state;
		return(
			<YouTube video={video.videoId} width={640} height={390} />
		)
	}
}
```

**Comment by goto-bus-stop** [comment]
looks like we should use cueVideoById instead of loadVideoById here, _if_ autoplay is false:

https://github.com/u-wave/react-youtube/blob/master/src/index.js#L150-L154
