### ISSUE TITLE
Feature Request:  getDuration() and getCurrentTime() support please

### ISSUE THREAD

**Issue by cjmling** [u-wave/react-youtube#25]
I tried to look into doc if it already support but doesn't seems like.

Will be nice to have this support. Personally I want to able to do stuff when player played till certain times/percent. 

I tried `setInterval` in `createPlayer` and was able to get the data. 

Sample codes can be seen here.  
http://www.opimedia.be/DS/webdev/YouTube/

```
var current = youTubePlayer.getCurrentTime();
var duration = youTubePlayer.getDuration();
```

**Comment by goto-bus-stop** [comment]
You can get a reference to the YouTube Player object by doing something like:
```js
<YouTube
  onReady={(event) => {
    const youTubePlayer = event.target
    // now you can do:
    youTubePlayer.getCurrentTime()
  }}
/>
```

**Comment by cjmling** [comment]
Ok that should work great :D 

 but currently , it never called back? https://github.com/u-wave/react-youtube/issues/26
