### ISSUE TITLE
Outdated event in eventNames.js ?

### ISSUE THREAD

**Issue by cjmling** [u-wave/react-youtube#26]
Based on this issue https://github.com/u-wave/react-youtube/issues/25  , the callback never called. It work only if i changed to this.

`onReady: onReady`

Seems like this whole file need to be updated.
https://developers.google.com/youtube/iframe_api_reference#Events

https://github.com/u-wave/react-youtube/blob/2c357c5aa72218890691b7bdb58d65616d6bce09/src/eventNames.js#L2

**Comment by goto-bus-stop** [comment]
dang, you're­ right—i only use the onPlaying/onPause handlers which were implemented differently so this slipped. thanks!

**Comment by goto-bus-stop** [comment]
this and the autoplay issue are addressed in :package: v0.6.0
